# Generated by Django 3.0.8 on 2020-07-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('Name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'testtable',
            },
        ),
    ]
